spring:
  security:
    user:
      password: password
  datasource:
    url: jdbc:h2:~/wcc-test-db;DB_CLOSE_ON_EXIT=TRUE
  jpa:
    hibernate:
      ddl-auto: update
    database-platform: org.hibernate.dialect.H2Dialect
    show-sql: false
    open-in-view: false

springdoc:
  swagger-ui:
    path: /swagger-ui.html
  api-docs:
    path: /api-docs

logging:
  level:
    mktany2k.wcc: debug